customer/urls.py
from . import views
from django.urls import path
from django.conf.urls import handler404,handler500

app_name = 'customer'

urlpatterns = [
    path('', views.index,name='index'),
    path('<int:id>', views.detail_loan_customer,name='detail_loan_customer'),
    path('add_user_customer/<int:id>', views.add_user_customer,name='add_user_customer'),
    path('add_repeat_order/<int:id>', views.add_repeat_order,name='add_repeat_order'),
    path('revision_loan', views.revision_loan,name='revision_loan'),
    path('custmer_repeatorder/<int:id>/<int:custid>/', views.custmer_repeatorder,name='custmer_repeatorder')
]

handler404 = 'views.handler404'

loan/urls.py
from . import views
from django.urls import path
from django.conf.urls import handler404,handler500

app_name = 'loan'
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:id>', views.detail_status,name='detail_status'),
    path('add_status_loan/<int:id>', views.add_status_loan,name='add_status_loan'),
]

handler404 = 'views.handler404'

simple_loan/urls.py
from . import views
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.dashboard),
    #path('loan/',include('loan.urls'),namespace='loan'),
    path('customer/',include('customer.urls',namespace='customer')),
    path('loan/',include('loan.urls',namespace='loan')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

customer/models.py
from django.db import models
from loan.models import Loan

class Customer(models.Model):
       GENDER_CHOICES = (
                             ('M', 'Male'),
                             ('F', 'Female'),
                            )
       gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
       first_name = models.CharField(max_length=15)
       last_name = models.CharField(max_length=15)
       email = models.CharField(max_length=50)
       password = models.TextField()
       date_birth = models.DateField()
       phone= models.CharField(max_length=20)
       npwp= models.CharField(max_length=20)
       ktp=  models.CharField(max_length=20)

class Customers_rel_loan(models.Model):
       custid   = models.ForeignKey(Customer,on_delete=models.CASCADE)
       loanid    = models.ForeignKey(Loan,on_delete=models.CASCADE)
       loans     = models.IntegerField()
       time_period = models.IntegerField(default=None, blank=True, null=True)
       interest_rate = models.FloatField(default=None, blank=True, null=True)
       installment = models.IntegerField(default=None, blank=True, null=True)
       interest_monthly = models.IntegerField(default=None, blank=True, null=True)
       status = models.CharField(max_length=10,default=None, blank=True, null=True)
       created_at = models.DateTimeField(auto_now_add = True)

customer/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from loan.models import Loan
from . models import Customer
from . models import Customers_rel_loan


def handler404(request):
       return render(request,'404.html',status=404)

def index(request):
       Customers_rel_loan_cust = Customers_rel_loan()
       customer     = Customer.objects.all()
       rel_customer = Customers_rel_loan.objects.filter(custid_id__in=customer).select_related()
       #// make out in HttpResponse
       # output = ', '.join([str(loan) for loan in loans])
       return render(request,'customer/index.html',{'customer':customer,'rel_customer':rel_customer})


def detail_loan_customer(request,id):
       Customers_rel_loan_cust = Customers_rel_loan()
       customer        = Customer.objects.filter(id=id)
       loan            = Customers_rel_loan.objects.filter(custid=id).all().select_related('custid').select_related('loanid')
       # thumbnail_list = []
       # for l in loan:
       #     l_info = {}
       #     l_info['title_loan'] = l.title
       #     thumbnail_list.append(l_info)
       # for l in loans:
       #     xa = {}
       #     xa['loans'] = l
       #     thumbnail_list.append(xa)
       # zipped = [list(t) for t in zip(loan, loans)]
       #loan.append(loans)
       # for l in loan:
       #     print (l.title)
       #rel_customer = Customers_rel_loan.objects.filter(custid_id__in=customer).select_related()
       #loanid = Customers_rel_loan.objects.filter(custid_id__in=18).select_related()
       #return HttpResponse(loan)
       return render(request,'customer/detail_loan.html',{'loan':loan,'customer':customer})

def add_user_customer(request,id):
       # print('OKE')
       print(request)

       customer = Customer()
       customers_rel_loan = Customers_rel_loan()
       loan = Loan()
       if request.method == 'POST':
              if request.POST['jangka_waktu'] == 36:
                     jangka_waktu = 3
              elif request.POST['jangka_waktu'] == 24:
                     jangka_waktu = 2
              else :
                     jangka_waktu = 1
              customer.first_name  = request.POST['first_name']
              customer.last_name = request.POST['last_name']
              customer.gender = request.POST['gender']
              customer.date_birth = request.POST['birthdate']
              customer.phone = request.POST['phone']
              customer.ktp = request.POST['ktp']
              customer.npwp = request.POST['npwp']
              customer.email = request.POST['email']
              customer.save()

              customers_rel_loan.custid_id = customer.id
              customers_rel_loan.loanid_id = id
              customers_rel_loan.status = 'onprogres'
              customers_rel_loan.loans = request.POST['jumlah_pinjaman']
              customers_rel_loan.interest_rate = request.POST['bunga']
              customers_rel_loan.time_period = request.POST['jangka_waktu']
              customers_rel_loan.interest_monthly = ((int(request.POST['jumlah_pinjaman']) * float(request.POST['bunga']) * jangka_waktu) / int(request.POST['jangka_waktu']) )/100
              customers_rel_loan.installment = (int(request.POST['jumlah_pinjaman']) / int(request.POST['jangka_waktu']))+ customers_rel_loan.interest_monthly
              customers_rel_loan.save()
              return HttpResponseRedirect('/loan')

def add_repeat_order(request,id):
       # print('OKE')
       customer = Customer()
       customers_rel_loan = Customers_rel_loan()
       loan = Loan()
       if request.method == 'POST':
              if request.POST['jangka_waktu'] == 36:
                     jangka_waktu = 3
              elif request.POST['jangka_waktu'] == 24:
                     jangka_waktu = 2
              else :
                     jangka_waktu = 1

              customers_rel_loan.custid_id = request.POST['custid']
              customers_rel_loan.loanid_id = id
              customers_rel_loan.status = 'onprogres'
              customers_rel_loan.loans = request.POST['jumlah_pinjaman']
              customers_rel_loan.interest_rate = request.POST['bunga']
              customers_rel_loan.time_period = request.POST['jangka_waktu']
              customers_rel_loan.interest_monthly = ((int(request.POST['jumlah_pinjaman']) * float(request.POST['bunga']) * jangka_waktu) / int(request.POST['jangka_waktu']) )/100
              customers_rel_loan.installment = (int(request.POST['jumlah_pinjaman']) / int(request.POST['jangka_waktu']))+ customers_rel_loan.interest_monthly
              customers_rel_loan.save()
              return HttpResponseRedirect('/loan')

def revision_loan(request):
       customers_rel_loan = Customers_rel_loan()
       id = request.POST['id']
       if request.POST.get('jangka_waktu') == 36:
              jangka_waktu = 3
       elif request.POST.get('jangka_waktu') == 24:
              jangka_waktu = 2
       else :
              jangka_waktu = 1
       custid     = request.POST.get('customer_id')
       cust       = Customers_rel_loan.objects.get(id=id)
       cust.loans = request.POST.get('jumlah_pinjaman')
       cust.interest_rate = request.POST.get('bunga')
       cust.time_period = request.POST.get('jangka_waktu')
       cust.status = request.POST.get('status')
       cust.interest_monthly = ((int(request.POST.get('jumlah_pinjaman')) * float(request.POST.get('bunga')) * jangka_waktu) / int(request.POST.get('jangka_waktu')) )/100
       cust.installment = (int(request.POST.get('jumlah_pinjaman')) / int(request.POST.get('jangka_waktu')))+ cust.interest_monthly

       cust.save()

       return HttpResponseRedirect('/customer/'+custid)

def custmer_repeatorder(request,id,custid):
       customer        = Customer.objects.filter(id=custid)
       #return HttpResponse(customer)
       return render(request,'customer/repeat_order.html',{'customer':customer,'loanid':id})

customer/templates/customer/index.html
{% extends 'template.html'%}

{%block title%}
       Customers-page
{%endblock%}

{%block content%}
 <h3 class="page-title">
     Nasabah
 </h3>


<div class="page-bar">
    <ul class="page-breadcrumb">
           <li>
                  <i class="fa fa-home"></i>
                  <a href="{{'/'}}">Home</a>
                  <i class="fa fa-angle-right"></i>
           </li>
           <li>
                  <a href="{{'/customer'}}">Nasabah</a>
           </li>
    </ul>
    <div class="page-toolbar">
           <div id="dashboard-report-range" class="pull-right tooltips btn btn-fit-height grey-salt" data-placement="top" data-original-title="Change dashboard date range">
                  <i class="icon-calendar"></i>&nbsp;
                  <span class="thin uppercase visible-lg-inline-block">&nbsp;</span>&nbsp;
                  <i class="fa fa-angle-down"></i>
           </div>
    </div>
</div>
<div class="col-md-12">
   <div class="col-md-12">
        <div class="portlet-body flip-scroll">
            <table class="table table-bordered table-striped table-condensed flip-content">
            <thead class="flip-content">
            <tr>
                <th width="20%">
                        Nama Nasabah
                </th>
                <th>
                        Email Nasabah
                </th>
                <th>
                </th>
            </tr>
            </thead>
            <tbody>
                {% for l in customer%}
                <tr>
                    <td>{{l.first_name}} {{l.last_name}}</td>
                    <td>{{l.email}}</td>
                    <td>
                        <a class="btn btn-default" href="{%url 'customer:detail_loan_customer' id=l.id %}">Detail</a>
                    </td>
                </tr>
                {% endfor%}

            </tbody>
            </table>
        </div>
   </div>
</div>

{%endblock%}

customer/templates/customer/repeat_order.html
{% extends 'template.html'%}
{%block title%}
       {{loan.title}}
{%endblock%}
{%block content%}
 <h3 class="page-title">
     Pinjaman Kembali <small>Pinjaman</small>
 </h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
           <li>
                  <i class="fa fa-home"></i>
                  <a href="{{'/'}}">Home</a>
                  <i class="fa fa-angle-right"></i>
           </li>
           <li>
                  <a href="{{'/loan'}}">Pinjaman</a>
                  <i class="fa fa-angle-right"></i>
           </li>
           <li>
                  <i>Pinjaman Kembali</i>
           </li>
    </ul>
    <div class="page-toolbar">
           <div id="dashboard-report-range" class="pull-right tooltips btn btn-fit-height grey-salt" data-placement="top" data-original-title="Change dashboard date range">
                  <i class="icon-calendar"></i>&nbsp;
                  <span class="thin uppercase visible-lg-inline-block">&nbsp;</span>&nbsp;
                  <i class="fa fa-angle-down"></i>
           </div>
    </div>
</div>
<div style="clear: both; width: 100%; height: 25px"></div>
<div class="col-md-12">
    <!-- TESTING -->
    <div class="portlet box grey-cascade">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>Informasi Data Nasabah
            </div>
            <div class="tools" >
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            {% for c in customer %}
            <form action="{% url 'customer:add_repeat_order' loanid%}" method="post" class="horizontal-form">
                {% csrf_token %}
                <div class="form-body">
                    <h3 class="form-section"><b>Data Diri</b></h3>
                    <input type="hidden" id="custid" name="custid" class="form-control" value="{{c.id}}" placeholder="Anif">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Nama Awal</label>
                                <input type="text" id="firstName" name="first_name" class="form-control" value="{{c.first_name}}" placeholder="Anif">
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Nama Belakang</label>
                                <input type="text" id="lastName" name="last_name" class="form-control" value="{{c.last_name}}"  placeholder="Maulana">
                            </div>
                        </div>
                        <!--/span-->
                    </div>
                    <!--/row-->
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Jenis Kelamin</label>
                                <select class="form-control" name="gender">
                                    <option value="m">Male</option>
                                    <option value="f">Female</option>
                                </select>
                            </div>
                        </div>
                        <!--/span-->
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label col-md-12" style="position: relative; left: -15px">Tanggal Lahir</label>
                                <input type="text"  name="birthdate" data-date-format="yyyy-mm-dd"  class="col-md-5 form-control form-control-inline input-medium date-picker"  placeholder="yyyy-mm-dd"  value="{{c.date_birth |date:"Y-m-d" }}" readonly>
                                <span class="input-group-btn col-md-7" style="position: relative; left: -13px">
                                    <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                                </span>
                            </div>
                        </div>
                        <!--/span-->
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Nomer Telfon</label>
                                <input type="text" class="form-control" name="phone" value="{{c.phone}}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">No KTP</label>
                                <input type="text" class="form-control" name="ktp" value="{{c.ktp}}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">No NPWP</label>
                                <input type="text" class="form-control" name="npwp" value="{{c.npwp}}">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Email</label>
                                <input type="text" class="form-control" name="email" value="{{c.email}}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Jumlah Pinjaman</label>
                                <input type="text" class="form-control" name="jumlah_pinjaman">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Jangka Waktu</label>
                                <select class="form-control" name="jangka_waktu">
                                    <option value="12">12</option>
                                    <option value="24">24</option>
                                    <option value="36">36</option>
                                </select>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Bunga</label>
                                <input type="text" class="form-control" name="bunga">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <button type="button" class="btn default">Batal</button>
                    <button type="submit" class="btn blue"><i class="fa fa-check"></i> Simpan</button>
                </div>
            </form>
            {%endfor%}
            <!-- END FORM-->
        </div>
    </div>
</div>
<div class="col-md-12">
</div>
{%endblock%}