loan/urls.py
from . import views
from django.urls import path
from django.conf.urls import handler404,handler500

app_name = 'loan'
urlpatterns = [
    path('', views.index,name='index'),
    path('<int:id>', views.detail_status,name='detail_status'),
    path('add_status_loan/<int:id>', views.add_status_loan,name='add_status_loan'),
]

handler404 = 'views.handler404'

simple_loan/urls.py
from . import views
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.dashboard),
    #path('loan/',include('loan.urls'),namespace='loan'),
    path('customer/',include('customer.urls',namespace='customer')),
    path('loan/',include('loan.urls',namespace='loan')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

loan/models.py
from django.db import models

class Loan(models.Model):
       title = models.CharField(max_length = 100)
       desc = models.TextField()
       created_at = models.DateTimeField(auto_now_add = True)

class status_loan(models.Model):
       status  = models.ForeignKey(Loan,on_delete=models.CASCADE)
       desc    = models.TextField()
       created_at = models.DateTimeField(auto_now_add = True)

loan/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,HttpResponseRedirect
from . models import Loan
from customer.models import Customer
from customer.models import Customers_rel_loan



def handler404(request):
       return render(request,'404.html',status=404)

def index(request):
       loan = Loan.objects.all()
       #customer = Customers_rel_loan.objects.filter(status='paid').all().select_related('custid').distinct('custid_id')
       customer = Customers_rel_loan.objects.exclude(custid_id__in = Customers_rel_loan.objects.filter(status='onprogres').values_list('custid_id', flat=True)).distinct('custid_id')
       #// make out in HttpResponse
       # output = ', '.join([str(loan) for loan in loans])
       # return HttpResponse(output)
       return render(request,'loan/index.html',{'loan':loan,'customer':customer})

def detail_status(request,id):

       #loans = Loan.objects.all()
       #loan = Loan.objects.get(pk = id)
       loan = get_object_or_404(Loan,pk=id)
       return render(request , 'loan/detail_status.html',{'loan':loan})

def add_status_loan(request,id):
       loan = get_object_or_404(Loan,pk=id)
       if request.method == 'POST':
              addDesc  = request.POST['desc']
              loan.status_loan_set.create(desc = addDesc)
              return HttpResponseRedirect('/loan')

loan/templates/loan/index.html
{% extends 'template.html'%}

{%block title%}
       Loan-page
{%endblock%}

{%block content%}
 <h3 class="page-title">
     Pinjaman
 </h3>

<div class="page-bar">
    <ul class="page-breadcrumb">
           <li>
                  <i class="fa fa-home"></i>
                  <a href="{{'/'}}">Home</a>
                  <i class="fa fa-angle-right"></i>
           </li>
           <li>
                  <a href="{{'/loan'}}">Pinjaman</a>
           </li>
    </ul>
    <div class="page-toolbar">
           <div id="dashboard-report-range" class="pull-right tooltips btn btn-fit-height grey-salt" data-placement="top" data-original-title="Change dashboard date range">
                  <i class="icon-calendar"></i>&nbsp;
                  <span class="thin uppercase visible-lg-inline-block">&nbsp;</span>&nbsp;
                  <i class="fa fa-angle-down"></i>
           </div>
    </div>
</div>
<div class="col-md-12">
    <div class="portlet-body flip-scroll">
        <table class="table table-bordered table-striped table-condensed flip-content">
        <thead class="flip-content">
        <tr>
            <th width="20%">
                    Nama Produk
            </th>
            <th>
                    Deskripsi Pinjaman
            </th>
            <th>
                Nasabah Baru
            </th>
            <th>
                Nasabah Lama
            </th>

        </tr>
        </thead>
        <tbody>
            {% for l in loan%}
            <tr>
                <td>{{l.title}}</td>
                <td>{{l.desc}}</td>
                <td>
                    <a class="btn btn-default" href="{%url 'loan:detail_status' id=l.id %}">Lihat</a>
                </td>
                <td>
                    <a class="btn btn-default ro_custold" data-toggle="modal" href="#ro_custold" loanid="{{l.id}}">Pinjaman Kembali</a>
                </td>
            </tr>
            {% endfor%}

        </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="ro_custold" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Pilih Nsabah</h4>
            </div>
            <div class="modal-body">
                    <table class="table table-bordered table-striped table-condensed flip-content">
                        <thead class="flip-content">
                        <tr>
                            <th width="70%">
                                    Nama Nasabah
                            </th>
                            <th>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for l in customer%}
                            <tr>
                                <td>{{l.custid.first_name}}  {{l.custid.last_name }}</td>
                                <td>
                                    <a class="btn btn-default choose_cust" data-toggle="modal" href="#ro_custold" loanid="" custid="{{l.custid.id}}">Pilih</a>
                                </td>
                            </tr>
                            {% endfor%}

                        </tbody>
                    </table>
                    <div style="clear: both; width: 100%; height: 15px"> </div>

            </div>
            <!-- <div class="modal-footer">
                <button type="button" class="btn default" data-dismiss="modal">Close</button>
                <button type="button" class="btn blue">Save changes</button>
            </div> -->
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

{%endblock%}